FROM node:20

RUN apt-get update && \
    apt-get install -y \
    fonts-noto-cjk \
    chromium \
    libnss3 \
    libatk-bridge2.0-0 \
    libx11-xcb1 \
    libgtk-3-0 \
    libxss1 \
    libasound2 \
    libgbm-dev && \
    rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium